---
title: "The Truth"
date: 2022-05-27 
--- 

title: The Truth
author: Jarod Wilson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website contains the cold, hard truth that people need to learn.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
